worker_processes 1;

events {
    worker_connections 512;
}

http {
    include       mime.types;
    default_type  text/html;

    # Remove server header
    server_tokens off;

    access_log off;

    server {
        listen 80;
        server_name _;

        location / {
            return 403;
            root /usr/share/nginx/html;
            error_page 403 /403.html;
        }

        location = /403.html {
            root /usr/share/nginx/html;
            internal;
        }
    }
}
